# Generated by Django 4.1.5 on 2023-12-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurseID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('address', models.TextField()),
                ('sex', models.CharField(max_length=10)),
                ('bloodType', models.CharField(max_length=5)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vitalID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('heartRate', models.IntegerField(null=True)),
                ('bloodPressure', models.CharField(max_length=15, null=True)),
                ('respiratoryRate', models.IntegerField(null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'dateTime')},
            },
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('treatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('treatment', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'dateTime')},
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('symptomID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('symptomDescripton', models.CharField(max_length=255)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'dateTime')},
            },
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('observationID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('observationDescription', models.CharField(max_length=255)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'dateTime')},
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicationID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('frequency', models.CharField(max_length=255)),
                ('medication', models.CharField(max_length=255)),
                ('prescriber', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'startDate')},
            },
        ),
        migrations.CreateModel(
            name='LogViewing',
            fields=[
                ('logViewingID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('nurse', 'dateTime')},
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('careID', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('dateTimeCompleted', models.DateTimeField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'dateTimeCompleted')},
            },
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('allergyID', models.AutoField(primary_key=True, serialize=False)),
                ('allergyDescription', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'allergyDescription')},
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admissionID', models.AutoField(primary_key=True, serialize=False)),
                ('admissionReason', models.TextField()),
                ('admissionDateTime', models.DateTimeField()),
                ('dischargeDateTime', models.DateTimeField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.nurse')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
            options={
                'unique_together': {('patient', 'admissionDateTime')},
            },
        ),
    ]
