# Generated by Django 5.0 on 2024-02-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursepal', '0002_nurse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='dischargeDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nursepal.nurse'),
        ),
    ]
