# Generated by Django 5.0 on 2024-02-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursepal', '0003_alter_admission_dischargedatetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checked', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursepal.patient')),
            ],
        ),
    ]
