# Generated by Django 5.0 on 2024-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursepal', '0004_careplanchecklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='careplanchecklistitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
