# Generated by Django 5.0 on 2024-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursepal', '0009_rename_symptomdescripton_symptoms_symptomdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='frequency',
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
