# Generated by Django 5.0 on 2024-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursepal', '0011_remove_careplanchecklistitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='maxDiastolicBloodPressure',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='maxHeartRate',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='maxRespiratoryRate',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='maxSystolicBloodPressure',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='maxTemperature',
            field=models.DecimalField(decimal_places=2, default=38, max_digits=5),
            preserve_default=False,
        ),
    ]
